=== Bertrandbenj/XML/bin/src/main/resources/dtd.dtd
<!ELEMENT Root (document*)>
<!ELEMENT document (wrd*)>
<!ELEMENT wrd EMPTY>
<!ATTLIST wrd cnt CDATA #REQUIRED>
<!ATTLIST wrd lemme CDATA #REQUIRED>
<!ATTLIST document name CDATA #REQUIRED>

=== Bertrandbenj/XML/JDOMOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root SYSTEM "src/main/resources/dtd.dtd">
<Root>
  <document name="emea-fr-dev.xml">
    <wrd cnt="279" lemme="être" />
    <wrd cnt="105" lemme="avoir" />
    <wrd cnt="94" lemme="patient" />
    <wrd cnt="87" lemme="Angiox" />
    <wrd cnt="86" lemme="bivalirudine" />
    <wrd cnt="79" lemme="cln" />
    <wrd cnt="66" lemme="saignement" />
    <wrd cnt="64" lemme="chez" />
    <wrd cnt="59" lemme="devoir" />
    <wrd cnt="48" lemme="milligramme" />
    <wrd cnt="44" lemme="pas" />
    <wrd cnt="39" lemme="utiliser" />
    <wrd cnt="36" lemme="traitement" />
    <wrd cnt="36" lemme="perfusion" />
    <wrd cnt="35" lemme="indésirable" />
    <wrd cnt="35" lemme="effet" />
    <wrd cnt="35" lemme="étude" />
    <wrd cnt="34" lemme="plus" />
    <wrd cnt="32" lemme="pouvoir" />
    <wrd cnt="31" lemme="ICP" />
    <wrd cnt="31" lemme="après" />
    <wrd cnt="31" lemme="solution" />
    <wrd cnt="29" lemme="inhibiteur" />
    <wrd cnt="28" lemme="dose" />
    <wrd cnt="27" lemme="médicament" />
    <wrd cnt="27" lemme="présenter" />
    <wrd cnt="26" lemme="site" />
    <wrd cnt="26" lemme="administrer" />
    <wrd cnt="23" lemme="hémorragie" />
    <wrd cnt="23" lemme="autre" />
    <wrd cnt="21" lemme="bolu" />
    <wrd cnt="21" lemme="rénal" />
    <wrd cnt="21" lemme="héparine" />
    <wrd cnt="21" lemme="SCA" />
    <wrd cnt="20" lemme="thrombine" />
    <wrd cnt="19" lemme="tout" />
    <wrd cnt="19" lemme="non" />
    <wrd cnt="19" lemme="traiter" />
    <wrd cnt="19" lemme="médecin" />
    <wrd cnt="19" lemme="intervention" />
    <wrd cnt="18" lemme="intraveineux" />
    <wrd cnt="18" lemme="réaction" />
    <wrd cnt="18" lemme="utilisation" />
    <wrd cnt="18" lemme="sanguin" />
    <wrd cnt="17" lemme="risque" />
    <wrd cnt="17" lemme="clinique" />
    <wrd cnt="17" lemme="voir" />
    <wrd cnt="17" lemme="fréquent" />
    <wrd cnt="17" lemme="majeur" />
    <wrd cnt="17" lemme="mise" />
    <wrd cnt="16" lemme="ACT" />
    <wrd cnt="16" lemme="atteindre" />
    <wrd cnt="15" lemme="de_le" />
    <wrd cnt="15" lemme="insuffisance" />
    <wrd cnt="15" lemme="heure" />
    <wrd cnt="15" lemme="flacon" />
    <wrd cnt="15" lemme="millilitre" />
    <wrd cnt="14" lemme="coagulation" />
    <wrd cnt="14" lemme="pendant" />
    <wrd cnt="14" lemme="troubles" />
    <wrd cnt="14" lemme="subir" />
    <wrd cnt="14" lemme="ACUITY" />
    <wrd cnt="14" lemme="comme" />
    <wrd cnt="13" lemme="produit" />
    <wrd cnt="13" lemme="information" />
    <wrd cnt="13" lemme="sans" />
    <wrd cnt="13" lemme="anticoagulant" />
    <wrd cnt="13" lemme="autorisation" />
    <wrd cnt="13" lemme="administration" />
    <wrd cnt="13" lemme="observer" />
    <wrd cnt="13" lemme="poudre" />
    <wrd cnt="13" lemme="recevoir" />
    <wrd cnt="13" lemme="IIb/IIIa" />
    <wrd cnt="13" lemme="contenir" />
    <wrd cnt="12" lemme="cardiaque" />
    <wrd cnt="12" lemme="également" />
    <wrd cnt="12" lemme="donnée" />
    <wrd cnt="12" lemme="concentration" />
    <wrd cnt="12" lemme="notice" />
    <wrd cnt="12" lemme="diluer" />
    <wrd cnt="12" lemme="douleur" />
    <wrd cnt="11" lemme="coronaire" />
    <wrd cnt="11" lemme="rapporter" />
    <wrd cnt="11" lemme="suivant" />
    <wrd cnt="11" lemme="suivre" />
    <wrd cnt="11" lemme="bénéficier" />
    <wrd cnt="11" lemme="en_cas_de" />
    <wrd cnt="11" lemme="degré" />
    <wrd cnt="10" lemme="avant" />
    <wrd cnt="10" lemme="peu" />
    <wrd cnt="10" lemme="moins" />
    <wrd cnt="10" lemme="conserver" />
    <wrd cnt="10" lemme="voie" />
    <wrd cnt="10" lemme="procédure" />
    <wrd cnt="10" lemme="recommander" />
    <wrd cnt="10" lemme="caillot" />
    <wrd cnt="10" lemme="tableau" />
    <wrd cnt="9" lemme="hypersensibilité" />
    <wrd cnt="9" lemme="critère" />
    <wrd cnt="9" lemme="poids" />
    <wrd cnt="9" lemme="ponction" />
    <wrd cnt="9" lemme="formation" />
    <wrd cnt="9" lemme="produire" />
    <wrd cnt="9" lemme="durée" />
    <wrd cnt="9" lemme="relative" />
    <wrd cnt="9" lemme="environ" />
    <wrd cnt="9" lemme="aspirine" />
    <wrd cnt="9" lemme="clopidogrel" />
    <wrd cnt="9" lemme="injectable" />
    <wrd cnt="8" lemme="durant" />
    <wrd cnt="8" lemme="cla" />
    <wrd cnt="8" lemme="vue" />
    <wrd cnt="8" lemme="condition" />
    <wrd cnt="8" lemme="minute" />
    <wrd cnt="8" lemme="250" />
    <wrd cnt="8" lemme="ne_pas" />
    <wrd cnt="8" lemme="actif" />
    <wrd cnt="8" lemme="bras" />
    <wrd cnt="8" lemme="associer" />
    <wrd cnt="8" lemme="hémoglobine" />
    <wrd cnt="8" lemme="définir" />
    <wrd cnt="8" lemme="sévère" />
    <wrd cnt="8" lemme="concerner" />
    <wrd cnt="8" lemme="jusqu'à" />
    <wrd cnt="8" lemme="aigu" />
    <wrd cnt="8" lemme="événement" />
    <wrd cnt="8" lemme="système" />
    <wrd cnt="8" lemme="groupe" />
    <wrd cnt="7" lemme="titulaire" />
    <wrd cnt="7" lemme="sang" />
    <wrd cnt="7" lemme="syndrome" />
    <wrd cnt="7" lemme="quel" />
    <wrd cnt="7" lemme="pharmacocinétique" />
    <wrd cnt="7" lemme="prévenir" />
    <wrd cnt="7" lemme="immédiatement" />
    <wrd cnt="7" lemme="nécessaire" />
    <wrd cnt="7" lemme="épar" />
    <wrd cnt="7" lemme="très" />
    <wrd cnt="7" lemme="contrôler" />
    <wrd cnt="7" lemme="mineur" />
    <wrd cnt="7" lemme="chute" />
    <wrd cnt="7" lemme="jour" />
    <wrd cnt="7" lemme="lier" />
    <wrd cnt="7" lemme="vouloir" />
    <wrd cnt="7" lemme="comment" />
    <wrd cnt="7" lemme="évaluer" />
    <wrd cnt="7" lemme="cas" />
    <wrd cnt="6" lemme="jours" />
    <wrd cnt="6" lemme="fréquence" />
    <wrd cnt="6" lemme="seul" />
    <wrd cnt="6" lemme="hépatique" />
    <wrd cnt="6" lemme="ANGIOX" />
    <wrd cnt="6" lemme="fréquemment" />
    <wrd cnt="6" lemme="temps" />
    <wrd cnt="6" lemme="0,1" />
    <wrd cnt="6" lemme="étudier" />
    <wrd cnt="6" lemme="1,75" />
    <wrd cnt="6" lemme="clad" />
    <wrd cnt="6" lemme="surveiller" />
    <wrd cnt="6" lemme="classe" />
    <wrd cnt="6" lemme="usage" />
    <wrd cnt="6" lemme="rubrique" />
    <wrd cnt="6" lemme="connaître" />
    <wrd cnt="6" lemme="rétropéritonéal" />
    <wrd cnt="6" lemme="allergique" />
    <wrd cnt="6" lemme="angiographie" />
    <wrd cnt="6" lemme="complet" />
    <wrd cnt="6" lemme="reconstituer" />
    <wrd cnt="6" lemme="humain" />
    <wrd cnt="6" lemme="1/10" />
    <wrd cnt="6" lemme="soit" />
    <wrd cnt="6" lemme="fonction" />
    <wrd cnt="6" lemme="signe" />
    <wrd cnt="6" lemme="enfant" />
    <wrd cnt="6" lemme="inclure" />
    <wrd cnt="6" lemme="âgé" />
    <wrd cnt="6" lemme="valeur" />
    <wrd cnt="6" lemme="plaquettaire" />
    <wrd cnt="6" lemme="intracrânien" />
    <wrd cnt="6" lemme="organes" />
    <wrd cnt="6" lemme="baser" />
    <wrd cnt="6" lemme="sujet" />
    <wrd cnt="6" lemme="seconde" />
    <wrd cnt="6" lemme="coronarien" />
    <wrd cnt="6" lemme="afin_de" />
    <wrd cnt="6" lemme="thoracique" />
    <wrd cnt="6" lemme="destiner" />
    <wrd cnt="6" lemme="indiquer" />
    <wrd cnt="6" lemme="percutané" />
    <wrd cnt="5" lemme="nécessiter" />
    <wrd cnt="5" lemme="véhicule" />
    <wrd cnt="5" lemme="post-commercialisation" />
    <wrd cnt="5" lemme="coeur" />
    <wrd cnt="5" lemme="garde" />
    <wrd cnt="5" lemme="marché" />
    <wrd cnt="5" lemme="résumé" />
    <wrd cnt="5" lemme="conduire" />
    <wrd cnt="5" lemme="aussi" />
    <wrd cnt="5" lemme="liaison" />
    <wrd cnt="5" lemme="activer" />
    <wrd cnt="5" lemme="souffrir" />
    <wrd cnt="5" lemme="marche" />
    <wrd cnt="5" lemme="emballage" />
    <wrd cnt="5" lemme="problème" />
    <wrd cnt="5" lemme="cela" />
    <wrd cnt="5" lemme="efficacité" />
    <wrd cnt="5" lemme="forme" />
    <wrd cnt="5" lemme="plaquette" />
    <wrd cnt="5" lemme="prendre" />
    <wrd cnt="5" lemme="augmenter" />
    <wrd cnt="5" lemme="crise" />
    <wrd cnt="5" lemme="lorsque" />
    <wrd cnt="5" lemme="comparer" />
    <wrd cnt="5" lemme="exister" />
    <wrd cnt="5" lemme="arrêter" />
    <wrd cnt="5" lemme="d'autres" />
    <wrd cnt="5" lemme="choc" />
    <wrd cnt="5" lemme="CHMP" />
    <wrd cnt="5" lemme="blanc" />
    <wrd cnt="5" lemme="injection" />
    <wrd cnt="5" lemme="montrer" />
    <wrd cnt="5" lemme="surdosage" />
    <wrd cnt="5" lemme="0,25" />
    <wrd cnt="5" lemme="hématome" />
    <wrd cnt="5" lemme="selon" />
    <wrd cnt="5" lemme="angioplastie" />
    <wrd cnt="5" lemme="machine" />
    <wrd cnt="5" lemme="entre" />
    <wrd cnt="5" lemme="liste" />
    <wrd cnt="5" lemme="sous" />
    <wrd cnt="5" lemme="médical" />
    <wrd cnt="5" lemme="taux" />
    <wrd cnt="5" lemme="anaphylactique" />
    <wrd cnt="5" lemme="activité" />
    <wrd cnt="5" lemme="supplémentaire" />
    <wrd cnt="5" lemme="deux" />
    <wrd cnt="5" lemme="type" />
    <wrd cnt="5" lemme="expérience" />
    <wrd cnt="5" lemme="exposition" />
    <wrd cnt="5" lemme="informer" />
    <wrd cnt="5" lemme="date" />
    <wrd cnt="5" lemme="fractionner" />
    <wrd cnt="4" lemme="réduire" />
    <wrd cnt="4" lemme="notamment" />
    <wrd cnt="4" lemme="prudence" />
    <wrd cnt="4" lemme="modérer" />
    <wrd cnt="4" lemme="femme" />
    <wrd cnt="4" lemme="hémorragique" />
    <wrd cnt="4" lemme="sexe" />
    <wrd cnt="4" lemme="thrombose" />
    <wrd cnt="4" lemme="hôpital" />
    <wrd cnt="4" lemme="fatal" />
    <wrd cnt="4" lemme="reconstitution" />
    <wrd cnt="4" lemme="diminution" />
    <wrd cnt="4" lemme="manifeste" />
    <wrd cnt="4" lemme="manière" />
    <wrd cnt="4" lemme="0,5" />
    <wrd cnt="4" lemme="flux" />
    <wrd cnt="4" lemme="1/100" />
    <wrd cnt="4" lemme="toxicité" />
    <wrd cnt="4" lemme="additionnel" />
